In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("E:/sales data analysis project/used_car_sales_analysis/data/car_prices.csv")

In [7]:
df.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [8]:
df.shape

(558837, 16)

In [9]:
df.columns

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')

In [10]:
for column in df.columns:
    print(column)

year
make
model
trim
body
transmission
vin
state
condition
odometer
color
interior
seller
mmr
sellingprice
saledate

In [11]:
df.tail()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
558832,2015,Kia,K900,Luxury,Sedan,NaN,knalw4d4xf6019304,in,45.0,18255.0,silver,black,avis corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)
558833,2012,Ram,2500,Power Wagon,Crew Cab,automatic,3c6td5et6cg112407,wa,5.0,54393.0,white,black,i -5 uhlmann rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,automatic,5uxzw0c58cl668465,ca,48.0,50561.0,black,black,financial services remarketing (lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835,2015,Nissan,Altima,2.5 S,sedan,automatic,1n4al3ap0fc216050,ga,38.0,16658.0,white,black,enterprise vehicle exchange / tra / rental / t...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,Ford,F-150,XLT,SuperCrew,automatic,1ftfw1et2eke87277,ca,34.0,15008.0,gray,gray,ford motor credit company llc pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

In [12]:
df.dtypes

year              int64
make             object
model            object
trim             object
body             object
transmission     object
vin              object
state            object
condition       float64
odometer        float64
color            object
interior         object
seller           object
mmr             float64
sellingprice    float64
saledate         object
dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

In [14]:
df.isnull().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [15]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing

              Missing Values  Missing Percentage
year                       0                0.00
make                   10301                1.84
model                  10399                1.86
trim                   10651                1.91
body                   13195                2.36
transmission           65352               11.69
vin                        4                0.00
state                      0                0.00
condition              11820                2.12
odometer                  94                0.02
color                    749                0.13
interior                 749                0.13
seller                     0                0.00
mmr                       38                0.01
sellingprice              12                0.00
saledate                  12                0.00

In [16]:
missing.sort_values(
    by="Missing Values",
    ascending=False
)

              Missing Values  Missing Percentage
transmission           65352               11.69
body                   13195                2.36
condition              11820                2.12
trim                   10651                1.91
model                  10399                1.86
make                   10301                1.84
color                    749                0.13
interior                 749                0.13
odometer                  94                0.02
mmr                       38                0.01
sellingprice              12                0.00
saledate                  12                0.00
vin                        4                0.00
year                       0                0.00
state                      0                0.00
seller                     0                0.00

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df["vin"].duplicated().sum()

np.int64(8539)

In [19]:
df.nunique()

year                34
make                96
model              973
trim              1963
body                87
transmission         4
vin             550297
state               64
condition           41
odometer        172278
color               46
interior            17
seller           14263
mmr               1101
sellingprice      1887
saledate          3766
dtype: int64

In [20]:
df.describe()

,year,condition,odometer,mmr,sellingprice
count,558837.000000,547017.000000,558743.000000,558799.000000,558825.000000
mean,2010.038927,30.672365,68320.017767,13769.377495,13611.358810
std,3.966864,13.402832,53398.542821,9679.967174,9749.501628
min,1982.000000,1.000000,1.000000,25.000000,1.000000
25%,2007.000000,23.000000,28371.000000,7100.000000,6900.000000
50%,2012.000000,35.000000,52254.000000,12250.000000,12100.000000
75%,2013.000000,42.000000,99109.000000,18300.000000,18200.000000
max,2015.000000,49.000000,999999.000000,182000.000000,230000.000000

In [21]:
df["sellingprice"].describe()

count    558825.000000
mean      13611.358810
std        9749.501628
min           1.000000
25%        6900.000000
50%       12100.000000
75%       18200.000000
max      230000.000000
Name: sellingprice, dtype: float64

In [22]:
(df["sellingprice"] <= 0).sum()

np.int64(0)

In [23]:
df["mmr"].describe()

count    558799.000000
mean      13769.377495
std        9679.967174
min          25.000000
25%        7100.000000
50%       12250.000000
75%       18300.000000
max      182000.000000
Name: mmr, dtype: float64

In [24]:
(df["mmr"] <= 0).sum()

np.int64(0)

In [25]:
df["odometer"].describe()

count    558743.000000
mean      68320.017767
std       53398.542821
min           1.000000
25%       28371.000000
50%       52254.000000
75%       99109.000000
max      999999.000000
Name: odometer, dtype: float64

In [26]:
(df["odometer"] < 0).sum()

np.int64(0)

In [27]:
df["condition"].value_counts(
    dropna=False
).sort_index()

condition
1.0      7364
2.0     20790
3.0     10803
4.0     19922
5.0     11222
11.0       87
12.0       95
13.0       82
14.0      134
15.0      144
16.0      178
17.0      243
18.0      323
19.0    42281
21.0     9199
22.0     6057
23.0     8188
24.0     9326
25.0    12561
26.0    11912
27.0    16351
28.0    19178
29.0    18928
31.0     9222
32.0     9962
33.0    10619
34.0    17398
35.0    26750
36.0    23144
37.0    25938
38.0    18723
39.0    19920
41.0    23073
42.0    24328
43.0    24937
44.0    25514
45.0    12313
46.0    12634
47.0    11363
48.0    12712
49.0    13099
NaN     11820
Name: count, dtype: int64

In [30]:
df["saledate"] = pd.to_datetime(df["saledate"], errors="coerce")

In [31]:
df["saledate"].dtype

datetime64[ns, tzoffset('PST', 28800)]

In [32]:
df["saledate"].isnull().sum()

np.int64(163348)

In [33]:
df["sale_year"] = df["saledate"].dt.year

In [34]:
df[["saledate", "sale_year"]].head()

                   saledate  sale_year
0 2014-12-16 12:30:00+08:00     2014.0
1 2014-12-16 12:30:00+08:00     2014.0
2 2015-01-15 04:30:00+08:00     2015.0
3 2015-01-29 04:30:00+08:00     2015.0
4 2014-12-18 12:30:00+08:00     2014.0

In [35]:
df["vehicle_age"] = (
    df["sale_year"] - df["year"]
)

In [36]:
df[["year", "sale_year", "vehicle_age"]].head()

   year  sale_year  vehicle_age
0  2015     2014.0         -1.0
1  2015     2014.0         -1.0
2  2014     2015.0          1.0
3  2015     2015.0          0.0
4  2014     2014.0          0.0

In [37]:
(df["vehicle_age"] < 0).sum()

np.int64(201)

In [38]:
df["price_difference"] = (
    df["sellingprice"] - df["mmr"]
)

In [39]:
df[
    ["mmr", "sellingprice", "price_difference"]
].head()

       mmr  sellingprice  price_difference
0  20500.0       21500.0            1000.0
1  20800.0       21500.0             700.0
2  31900.0       30000.0           -1900.0
3  27500.0       27750.0             250.0
4  66000.0       67000.0            1000.0

In [40]:
df["price_difference_pct"] = (
    (df["sellingprice"] - df["mmr"])
    / df["mmr"]
) * 100

In [41]:
df[
    ["mmr", "sellingprice", "price_difference_pct"]
].head()

       mmr  sellingprice  price_difference_pct
0  20500.0       21500.0              4.878049
1  20800.0       21500.0              3.365385
2  31900.0       30000.0             -5.956113
3  27500.0       27750.0              0.909091
4  66000.0       67000.0              1.515152

In [42]:
df["sale_month"] = df["saledate"].dt.month

In [43]:
df["sale_month_name"] = (
    df["saledate"].dt.strftime("%B")
)

In [44]:
df["sale_quarter"] = (
    "Q" + df["saledate"].dt.quarter.astype(str)
)

In [45]:
df[
    [
        "year",
        "saledate",
        "sale_year",
        "vehicle_age",
        "mmr",
        "sellingprice",
        "price_difference",
        "price_difference_pct",
        "sale_month",
        "sale_month_name",
        "sale_quarter"
    ]
].head(10)

,year,saledate,sale_year,vehicle_age,mmr,sellingprice,price_difference,price_difference_pct,sale_month,sale_month_name,sale_quarter
0,2015,2014-12-16 12:30:00+08:00,2014.0,-1.0,20500.0,21500.0,1000.0,4.878049,12.0,December,Q4.0
1,2015,2014-12-16 12:30:00+08:00,2014.0,-1.0,20800.0,21500.0,700.0,3.365385,12.0,December,Q4.0
2,2014,2015-01-15 04:30:00+08:00,2015.0,1.0,31900.0,30000.0,-1900.0,-5.956113,1.0,January,Q1.0
3,2015,2015-01-29 04:30:00+08:00,2015.0,0.0,27500.0,27750.0,250.0,0.909091,1.0,January,Q1.0
4,2014,2014-12-18 12:30:00+08:00,2014.0,0.0,66000.0,67000.0,1000.0,1.515152,12.0,December,Q4.0
5,2015,2014-12-30 12:00:00+08:00,2014.0,-1.0,15350.0,10900.0,-4450.0,-28.990228,12.0,December,Q4.0
6,2014,2014-12-17 12:30:00+08:00,2014.0,0.0,69000.0,65000.0,-4000.0,-5.797101,12.0,December,Q4.0
7,2014,2014-12-16 13:00:00+08:00,2014.0,0.0,11900.0,9800.0,-2100.0,-17.647059,12.0,December,Q4.0
8,2014,2014-12-18 12:00:00+08:00,2014.0,0.0,32100.0,32250.0,150.0,0.467290,12.0,December,Q4.0
9,2014,2015-01-20 04:00:00+08:00,2015.0,1.0,26300.0,17500.0,-8800.0,-33.460076,1.0,January,Q1.0

In [46]:
categorical_columns = [
    "make",
    "model",
    "trim",
    "body",
    "transmission",
    "color",
    "interior"
]

for column in categorical_columns:
    df[column] = df[column].fillna("Unknown")

In [47]:
df[categorical_columns].isnull().sum()

make            0
model           0
trim            0
body            0
transmission    0
color           0
interior        0
dtype: int64

In [48]:
df = df.dropna(
    subset=["sellingprice"]
)

In [49]:
df["sellingprice"].isnull().sum()

np.int64(0)

In [50]:
df = df.dropna(
    subset=["saledate"]
)

In [51]:
df["saledate"].isnull().sum()

np.int64(0)

In [52]:
df_public = df.drop(
    columns=["vin"]
)

In [53]:
df_public.shape

(395489, 22)

In [54]:
df_public.info()

<class 'pandas.core.frame.DataFrame'>
Index: 395489 entries, 0 to 403182
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   year                  395489 non-null  int64
 1   make                  395489 non-null  object
 2   model                 395489 non-null  object
 3   trim                  395489 non-null  object
 4   body                  395489 non-null  object
 5   transmission          395489 non-null  object
 6   state                 395489 non-null  object
 7   condition             383696 non-null  float64
 8   odometer              395406 non-null  float64
 9   color                 395489 non-null  object
 10  interior              395489 non-null  object
 11  seller                395489 non-null  object
 12  mmr                   395489 non-null  float64
 13  sellingprice          395489 non-null  float64
 14  saledate              395489 non-null  datetime64[ns, tzoffset('PST', 28800)]
 15  sale_year             395489 non-null  float64
 16  vehicle_age           395489 non-null  float64
 17  price_difference      395489 non-null  float64
 18  price_difference_pct  395489 non-null  float64
 19  sale_month            395489 non-null  float64
 20  sale_month_name       395489 non-null  object
 21  sale_quarter          395489 non-null  object
dtypes: datetime64[ns, tzoffset('PST', 28800)](1), float64(9), int64(1), object(11)
memory usage: 69.4+ MB

In [55]:
df_public.head()

,year,make,model,trim,body,transmission,state,condition,odometer,color,...,mmr,sellingprice,saledate,sale_year,vehicle_age,price_difference,price_difference_pct,sale_month,sale_month_name,sale_quarter
0,2015,Kia,Sorento,LX,SUV,automatic,ca,5.0,16639.0,white,...,20500.0,21500.0,2014-12-16 12:30:00+08:00,2014.0,-1.0,1000.0,4.878049,12.0,December,Q4.0
1,2015,Kia,Sorento,LX,SUV,automatic,ca,5.0,9393.0,white,...,20800.0,21500.0,2014-12-16 12:30:00+08:00,2014.0,-1.0,700.0,3.365385,12.0,December,Q4.0
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,ca,45.0,1331.0,gray,...,31900.0,30000.0,2015-01-15 04:30:00+08:00,2015.0,1.0,-1900.0,-5.956113,1.0,January,Q1.0
3,2015,Volvo,S60,T5,Sedan,automatic,ca,41.0,14282.0,white,...,27500.0,27750.0,2015-01-29 04:30:00+08:00,2015.0,0.0,250.0,0.909091,1.0,January,Q1.0
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,ca,43.0,2641.0,gray,...,66000.0,67000.0,2014-12-18 12:30:00+08:00,2014.0,0.0,1000.0,1.515152,12.0,December,Q4.0

In [56]:
final_missing = pd.DataFrame({
    "Missing Values": df_public.isnull().sum(),
    "Missing Percentage": (
        df_public.isnull().sum()
        / len(df_public)
        * 100
    ).round(2)
})

final_missing

                      Missing Values  Missing Percentage
year                               0                0.00
make                               0                0.00
model                              0                0.00
trim                               0                0.00
body                               0                0.00
transmission                       0                0.00
state                              0                0.00
condition                      11793                2.98
odometer                          83                0.02
color                              0                0.00
interior                           0                0.00
seller                             0                0.00
mmr                                0                0.00
sellingprice                       0                0.00
saledate                           0                0.00
sale_year                          0                0.00
vehicle_age                        0                0.00
price_difference                   0                0.00
price_difference_pct               0                0.00
sale_month                         0                0.00
sale_month_name                    0                0.00
sale_quarter                       0                0.00

In [57]:
df_public.duplicated().sum()

np.int64(0)

In [59]:
df_public.to_csv(
    "E:/sales data analysis project/used_car_sales_analysis/data/car_prices.csv",
    index=False
)

In [61]:
import os

os.path.exists(
    "E:/sales data analysis project/used_car_sales_analysis/data/car_prices_pt.csv"
)

False

In [62]:
import os

os.listdir(r"E:\sales data analysis project\used_car_sales_analysis\data")

['car_prices.csv']

In [63]:
import os

print(os.getcwd())

C:\Users\chaki

In [64]:
os.listdir()

['.anaconda',
 '.cache',
 '.codex',
 '.conda',
 '.continuum',
 '.copilot',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.vscode',
 '.vscode-shared',
 'AppData',
 'Application Data',
 'car_prices_pt.ipynb',
 'configuration-Office365-x64.xml',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'miniconda3',
 'Music',
 'My Documents',
 'my_py_proj',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{117f6b12-18e1-11f1-af3d-a6ebf7083675}.TxR.0.regtrans-ms',
 'NTUSER.DAT{117f6b12-18e1-11f1-af3d-a6ebf7083675}.TxR.1.regtrans-ms',
 'NTUSER.DAT{117f6b12-18e1-11f1-af3d-a6ebf7083675}.TxR.2.regtrans-ms',
 'NTUSER.DAT{117f6b12-18e1-11f1-af3d-a6ebf7083675}.TxR.blf',
 'NTUSER.DAT{117f6b13-18e1-11f1-af3d-a6ebf7083675}.TM.blf',
 'NTUSER.DAT{117f6b13-18e1-11f1-af3d-a6ebf7083675}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{117f6b13-18e1-11f1-af3d-a6ebf7083675}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Postman',
 'PrintHood',
 'Recent',
 'sales.ipynb',
 'Saved Games',
 'Searches',
 'SendTo',
 'setup.exe',
 'source',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']